# Generated by Django 6.0.2 on 2026-03-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_comment_author_alter_comment_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "Admin"), ("STAFF", "Staff"), ("USER", "User")],
                default="USER",
                max_length=16,
            ),
        ),
    ]
